<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Automation" duration-ms="87562" started-at="2018-03-09T19:29:05Z" finished-at="2018-03-09T19:30:33Z">
    <groups>
    </groups>
    <test name="Gudppl Automation Event" duration-ms="87562" started-at="2018-03-09T19:29:05Z" finished-at="2018-03-09T19:30:33Z">
      <class name="com.gudppl.Testcases.StoryCreateTestCase">
        <test-method status="PASS" signature="initializeTestBaseSetup(java.lang.String, java.lang.String)[pri:0, instance:com.gudppl.Testcases.StoryCreateTestCase@687080dc]" name="initializeTestBaseSetup" is-config="true" duration-ms="19666" started-at="2018-03-09T19:29:05Z" finished-at="2018-03-09T19:29:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://qa.gudppl.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestBaseSetup -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.gudppl.Testcases.StoryCreateTestCase@687080dc]" name="setUp" is-config="true" duration-ms="0" started-at="2018-03-09T19:29:25Z" finished-at="2018-03-09T19:29:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="commTest()[pri:1, instance:com.gudppl.Testcases.StoryCreateTestCase@687080dc]" name="commTest" duration-ms="20526" started-at="2018-03-09T19:29:25Z" finished-at="2018-03-09T19:29:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commTest -->
        <test-method status="FAIL" signature="testCeateStroy()[pri:2, instance:com.gudppl.Testcases.StoryCreateTestCase@687080dc]" name="testCeateStroy" duration-ms="47070" started-at="2018-03-09T19:29:45Z" finished-at="2018-03-09T19:30:32Z">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Cannot run program "E:\image\ImageNoticeUpload\ListingFundIamgeUpload4.exe": CreateProcess error=2, The system cannot find the file specified]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Cannot run program "E:\image\ImageNoticeUpload\ListingFundIamgeUpload4.exe": CreateProcess error=2, The system cannot find the file specified
at java.lang.ProcessBuilder.start(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at com.gudppl.gudstories.Pages.CreatePage.createStory(CreatePage.java:79)
at com.gudppl.Testcases.StoryCreateTestCase.testCeateStroy(StoryCreateTestCase.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
at java.lang.ProcessImpl.create(Native Method)
at java.lang.ProcessImpl.<init>(Unknown Source)
at java.lang.ProcessImpl.start(Unknown Source)
... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCeateStroy -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.gudppl.Testcases.StoryCreateTestCase@687080dc]" name="tearDown" is-config="true" duration-ms="278" started-at="2018-03-09T19:30:32Z" finished-at="2018-03-09T19:30:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.gudppl.Testcases.StoryCreateTestCase -->
    </test> <!-- Gudppl Automation Event -->
  </suite> <!-- Automation -->
</testng-results>
