<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BADJCCG" failures="0" tests="22" name="com.gudppl.Testcases.EventCreateTestcase" time="0.005" errors="2" timestamp="08 Mar 2018 15:29:34 GMT" skipped="20">
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.005">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.gudppl.event.Pages.BasePage.getPageTitle(BasePage.java:23)
at com.gudppl.Testcases.EventCreateTestcase.testCeateEvent(EventCreateTestcase.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="tearDown" time="0.000">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.gudppl.Testcases.EventCreateTestcase.tearDown(EventCreateTestcase.java:113)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
  <testcase classname="com.gudppl.Testcases.EventCreateTestcase" name="testCeateEvent" time="0.000">
    <skipped/>
  </testcase> <!-- testCeateEvent -->
</testsuite> <!-- com.gudppl.Testcases.EventCreateTestcase -->
